### PR TITLE
Wait when file is not written yet

### PR DESCRIPTION
**Pull request by viaccoz**
- A task is launched to dump lsass.exe. As long as it is not finished, the dump file is non-existent or empty. This can generate STATUS_OBJECT_NAME_NOT_FOUND errors. Because of this, we have to wait until the task and the write are finished.
- Delete dump file
- More precise logging

### CODE REVIEW

**Comment by viaccoz** [comment]
When the system is slow, the dump of lsass.exe can take a long time. In that case, the following error is thrown:
$ lsassy -d domain/user:password@target
[*] Authenticating against target
[+] Authenticated
[*] File \Windows\Temp\tmp.dmp deleted
[*] Old lsass dump was removed
[*] Using DLL Method (default)
[*] Register random task abcd0123
[+] Process lsass.exe was successfully dumped
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/impacket/smbconnection.py", line 545, in openFile
    securityFlags, oplockLevel, createContexts)
  File "/usr/local/lib/python3.7/dist-packages/impacket/smb3.py", line 982, in create
    if ans.isValidAnswer(STATUS_SUCCESS):
  File "/usr/local/lib/python3.7/dist-packages/impacket/smb3structs.py", line 437, in isValidAnswer
    raise smb3.SessionError(self['Status'], self)
impacket.smb3.SessionError: SMB SessionError: STATUS_OBJECT_NAME_NOT_FOUND(The object name is not found.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/lsassy/impacketconnection.py", line 83, in openFile
    fid = self.conn.openFile(tid, fpath, desiredAccess=FILE_READ_DATA)
  File "/usr/local/lib/python3.7/dist-packages/impacket/smbconnection.py", line 547, in openFile
    raise SessionError(e.get_error_code(), e.get_error_packet())
impacket.smbconnection.SessionError: SMB SessionError: STATUS_OBJECT_NAME_NOT_FOUND(The object name is not found.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/lsassy", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/dist-packages/lsassy/__main__.py", line 84, in run
    ifile.open(conn, file_path)
  File "/usr/local/lib/python3.7/dist-packages/lsassy/impacketfile.py", line 33, in open
    self._fid = self._conn.openFile(self._tid, self._fpath)
  File "/usr/local/lib/python3.7/dist-packages/lsassy/impacketconnection.py", line 91, in openFile
    raise Exception(e)
Exception: SMB SessionError: STATUS_OBJECT_NAME_NOT_FOUND(The object name is not found.)

**Comment by Hackndo** [comment]
Thank you, good catch ! And yes, I totally forgot a comment that deletes dump ;) Thanks !

**Comment by viaccoz** [comment]
Nice, thank you for your work! :)

**Comment by Hackndo** [comment]
Right after I merged your request and did some testing, I found another little bug, so don't forget to pull 1.0.2 :D
Again thanks for your contribution, helps a lot :)

**Pull request merged**
